[[accounts]]
access_token = '' # 账号的 access_token。从 dashboard 上获取
email = '' # 用来记录脚本处理了哪些邮箱。
refresh_token = '' # 账号的 refresh_token。从 dashboard 上获取
unique_ids = [''] # node 的 qunique id。从 dashboard 上获取。如果不想安装插件获取就使用 `unique_ids = "" ` 当前脚本会自动生成一个
update_timestamp = '' # 用来记录 config.toml 修改时间。

[global]
base_url = 'https://api.meshchain.ai/meshmain' # 项目方请求地址。写死
request_interval = 60 # 每次循环间隔 60s 可以修改